[package]
name = "rust-reach-www"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
